---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        run: demo
    spec:
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: demo-pvc
      containers:
      - name: app
        image: nginx
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: data-volume
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 2
